### ISSUE TITLE
Lexical or Preprocessor Issue

### ISSUE THREAD

**Issue by alexshive** [brion/OGVKit#126]
Running the example and getting a `vpx/vpx_decoder.h file not found`. Is there a location to get this?

**Comment by brion** [comment]
Hmm, that should be provided by the CocoaPods installation... did you run 'pod install' and load the workspace rather than the project directly?

```
$ cd OGVKit/Example
$ pod install
 ...
$ find . -name vpx_decoder.h
./Pods/Headers/Private/libvpx/vpx/vpx_decoder.h
./Pods/Headers/Public/libvpx/vpx/vpx_decoder.h
./Pods/libvpx/VPX.framework/Headers/vpx/vpx_decoder.h
```

**Comment by brion** [comment]
Ok I can totally reproduce that on a fresh install (with Xcode 7 beta on 10.11 beta, but not sure that matters).

Fixed with a hack in the spec for libvpx: https://github.com/brion/OGVKit-Specs/commit/7d6344a000491b1c3bf0682926a7704c4d06de24

Remove the Podfile.lock file and Pods directory and re-run 'pod install', it _should_ work now. :D
