### ISSUE TITLE
Backwards Playback

### ISSUE THREAD

**Issue by andyshephard** [brion/OGVKit#139]
Is it possible for the OGVKit to play video backwards? I've gone through most classes to try and determine if or even how it could be possible to play a video from the final frame to the first frame, but haven't managed to get any further during this discovery process.

Is this going to be a feature that could be implemented in the future, or if not, perhaps could you provide some insight into where I should look in order to incorporate this feature?

**Comment by brion** [comment]
Playing backwards is tricky; due to the way most videos are encoded frame-to-frame, you can only actually decode in the forward direction between keyframes. So to play backwards, you have to decode forwards from time T(k1) to time T(k2), then play the frames backwards from T(k2) to T(k1). This makes demands on both timing and memory pressure -- you either need to decode frames over and over, or hold a lot of frames in memory before displaying them -- and doesn't really fit well with the streaming data architecture of the decoder/player.

You might be better off encoding a second video that's reversed from the forward video, if you need a back-and-forth effect or looping that performs well; it's more data to download but a lot easier to rig up.

**Comment by andyshephard** [comment]
Thanks for the info Brion. I'll perhaps look at integrating the desired functionality a different way (seeking backwards 2 to 3 seconds every .25 seconds), and see what the visual effect of this would be like.

**Comment by andyshephard** [comment]
The seek function would possibly present the solution to my issue, though unfortunately the video is lacking cues, so 'libnestegg' is not able to process the request.

**Comment by andyshephard** [comment]
Is it possible to start the video from a certain point (4 seconds in) if it's a WEBM video without cues?

**Comment by brion** [comment]
Hmm, no I believe it's only able to seek to cue points. Actually I think the seeking on webm may need more work even for cue points... I'll have to double check the current status.

**Comment by andyshephard** [comment]
I ended up using an OGG video format instead, so seeking was possible.

**Comment by brion** [comment]
Closing out per above.
