### ISSUE TITLE
Cannot load resources if resources are manually moved to the application bundle

### ISSUE THREAD

**Issue by andyshephard** [brion/OGVKit#141]
The network stream works when playing on the simulator, but not on the device.
Will dig deeper into it, but checked with Instruments so far and didn't detect anything major.

**Comment by andyshephard** [comment]
By the way, the video I'm trying to play is 960x360. Wondering if there's an issue with the overall size.    
    
This is apparently what the iDevices can handle:
MPEG-4 video, up to 2.5 Mbps, 640 by 480 pixels, 30 frames per second, Simple Profile with AAC-LC audio up to 160 Kbps, 48kHz, stereo audio in .m4v, .mp4, and .mov file formats.

**Comment by brion** [comment]
Should play 1920x1080 or more just fine in terms of data reaching the screen... Do you have a sample stream you can link to for testing?

**Comment by andyshephard** [comment]
Sure:
http://andyshephard.com/samples/sampleVideo.ogv   
and   
http://andyshephard.com/samples/sampleVideo.mp4

**Comment by lukaszSliwaLogicIms** [comment]
Hi guys - sorry for my bad english. I found similar problem to this issue, video played on sim but not on device. Due to problems with Pods installation I added OGVKit to my project manually. After some time I finally solved this issue (at least for me). 

The problem lies in OGVFrameView and method
`-(GLuint)compileShader:(GLenum)shaderTyp`
 which doesn't properly load shaders. Quick fix - you must add 'Resources' folder to your project and change line 
`NSBundle *bundle = [[OGVKit singleton] resourceBundle];`
 to
 `NSBundle *bundle = [NSBundle mainBundle];`
This is quick fix if someone manually embed OGVKit in project. I don't know if this also apply to Pods installation.

**Comment by lukaszSliwaLogicIms** [comment]
Hi, at first sorry for my bad english :) I found similar issue but on manually embedded OGVKit in project. After a while I finally resolved it (at least for me). Problem lies in OGVFrameView and method:
`-(GLuint)compileShader:(GLenum)shaderType`
which doesn't properly load shaders in manual installation of OGVKit. Quick fix is to add "Resources" folder to project and change
`NSBundle *bundle = [[OGVKit singleton] resourceBundle];`
to 
`NSBundle *bundle = [NSBundle mainBundle];`
This is quick fix for manual installation. Probably it doesn't apply to Pod installation but unfortunately I cannot install OGVKit via CocoaPods.

**Comment by andyshephard** [comment]
@lukaszSliwaLogicIms It was exactly that issue. I actually had the same difficulties with installing OGVKit as a pod, but as I needed to edit some elements of the player view, rather than forking the project and making minor changes, I opted to install the library locally.

@brion Perhaps there should be a way to differentiate between pod installation and local installation, and assign the bundle object based on this?

`NSBundle *bundle = [[OGVKit singleton] resourceBundle];`
or
`NSBundle *bundle = [NSBundle mainBundle];`

**Comment by brion** [comment]
Catching up on old issues... what exactly does "manual installation mean"? Are you putting the resource files directly in your application's main app bundle instead of creating a bundle called "OGVKitResources.bundle" and including that bundle in the app?
