### ISSUE TITLE
Update opus to 1.2

### ISSUE THREAD

**Issue by brion** [brion/OGVKit#184]
opus 1.2 recently landed, should update.

Currently we seem to be using an externally-packaged cocoapods libopus dependency, which has not yet updated.

**Comment by Brahmasmi** [comment]
Opus 1.3 was released on 18th Oct 2018.

We may want to update to this release, especially since the changelog highlights:
"...
- Security/hardening improvements
..."

I may be wrong here, but since that cocoapods libopus dependency [2] can be considered abandoned, would it be better if we build libopus within the project? It could help keep us current with the codec releases.

Dhanyavaad.

[1] - http://opus-codec.org/release/stable/2018/10/18/libopus-1_3.html
[2] - https://cocoapods.org/pods/libopus
