### ISSUE TITLE
'skeleton.h' file not found

### ISSUE THREAD

**Issue by duf1991** [brion/OGVKit#214]
hi, why your project cannot build success, the reason is 'skeleton.h' file not found, please help me, I will be online for your reason, thank you very much!!

![ogg](https://user-images.githubusercontent.com/20440035/41149196-86c5ec48-6b3d-11e8-85b1-889c65ae1fbb.jpg)

**Comment by SasanSoroush** [comment]
no answer?

**Comment by duf1991** [comment]
no yet..

**Comment by oVuTruongGiang** [comment]
@duf1991 
If you just want to build Example project:
1. please clone by using `git clone https://github.com/brion/OGVKit` (not download zip file)
2. run `git submodule update --init --recursive`
Why? Because they use submodule to checkout skeleton framework.
3. Checkout to 'Example' folder and run `pod install`
4. Open xcodeworkspace file to use.

you cant import source code manually,  use Cocoapods instead.
