### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by deep-pradhan-fw** [brion/OGVKit#229]
[!] Error installing liboggz

**Comment by YankoSoulisimo** [comment]
Same here:

[!] Error installing liboggz
[!] /usr/bin/git clone https://git.xiph.org/liboggz.git /var/folders/lh/8rtrvwm54kl3p0p_r66zqx5r0000gp/T/d20200724-7513-htz0l2 --template=

Cloning into '/var/folders/lh/8rtrvwm54kl3p0p_r66zqx5r0000gp/T/d20200724-7513-htz0l2'...
fatal: unable to access 'https://git.xiph.org/liboggz.git/': Failed to connect to git.xiph.org port 443: Connection refused

It turned out that https://git.xiph.org/liboggz.git/ is now here --> https://gitlab.xiph.org/xiph/liboggz

How do we fix that in the specs?
